---
- name: configure OpenMPI on servers
  hosts: servers
  sudo: true
  vars:
  remote_user: root
  tasks:
   - authorized_key: user=cameronjloader key="{{ lookup('file', '/home/cameronjloader/.ssh/id_rsa.pub') }}"
   - name: configure machine for OpenMPI
     apt: name=build-essential update_cache=yes
   - name: install the required packages for OpenMPI
     action: apt package={{item}} state=installed
     with_items:
     - openmpi-bin 
     - openmpi-checkpoint
     - openmpi-common
     - openmpi-doc 
     - libopenmpi-dev
