---
- name: configure SSH on servers
  hosts: servers
  sudo: true
  vars:
  remote_user: root
  tasks:
  - name: Installing required essentials
    apt: name=build-essential state=installed
  - name: Generating SSH Keys
    user: name=root generate_ssh_key=yes
  - name: Obtaining Keys
    fetch: src=~/.ssh/id_rsa.pub dest=~/.ssh/tmp/ recursive=yes
  - name: Copying SSH keys to Machines
    copy: src=~/.ssh/ dest=~/.ssh/ directory_mode
  - name: Adding to the list of authorized_keys  
    shell: cat ~/.ssh/tmp/166.78.164.*/root/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
