---
- name: configure SSH on servers
  hosts: servers
  sudo: true
  vars:
  remote_user: root
  tasks:
  - name: Getting rid of old authorized_keys file
    command: rm .ssh/authorized_keys
  - name: Generating SSH Keys
    user: name=root generate_ssh_key=yes
  - name: Obtaining Keys
    fetch: src=~/.ssh/id_rsa.pub dest=inventory[1]/.ssh/tmp/ recursive=yes
  - name: Copying SSH keys to Machines
    synchronize: src=~/.ssh/tmp/ dest=~/.ssh/tmp recursive=yes
  - name: Adding to the list of authorized_keys  
    shell: cat inventory[1]/.ssh/tmp/166.78.164.*/root/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
