---
  hosts: servers
  sudo: true
  vars:
  remote_user: root
  tasks:
   - name: Removing OpenMPI from machines
     apt: name=build-essential state=absent
   - name: Removing the required packages for OpenMPI
     action: apt package={{item}} state=absent
     with_items:
     - openmpi-bin 
     - openmpi-checkpoint
     - openmpi-common
     - openmpi-doc 
     - libopenmpi-dev
