---
- name: configure SSH on servers
  hosts: servers
  sudo: true
  vars:
  remote_user: root
  tasks:
  - name: Generating SSH Keys
    user: name=root generate_ssh_key=yes
  - name: Obtaining Keys
    fetch: src=~/.ssh/id_rsa.pub dest= .ssh/tmp
  - name: Copying SSH keys to Machines
    synchronize: mode=pull src=.ssh/tmp dest=.ssh/tmp/
    delegate_to: 166.78.164.*
  - name: Adding to the list of authorized_keys  
    shell: cat ~/.ssh/tmp/166.78.164.*/root/.ssh/id_rsa.pub >> /root/.ssh/authorized_keys
