---
- name: configure SSH on servers
  hosts: servers
  sudo: true
  vars:
  remote_user: root
  tasks:
  - name: Generating SSH Keys
    user: name=root generate_ssh_key=yes
  - name: Obtaining Keys
    fetch: src=~/.ssh/id_rsa.pub dest=~/.ssh/tmp/
  - name: Copying SSH keys to authorized_keys
    command: cat ~/.ssh/tmp/166.78.62.*/root/* >> ~/.ssh/authorized_keys
