---
- name: configure SSH on servers
  hosts: servers
  sudo: true
  vars:
  remote_user: root ask_pass
  tasks:
  - name: Generating SSH Keys
    user: name=root generate_ssh_key=yes
  - name: Obtaining Keys
    fetch: src=~/.ssh/id_rsa.pub dest=~/Dropbox/ansible-openmpi/playbooks/.ssh/tmp/ recursive=yes
  - name: Copying SSH keys to Machines
    synchronize: src=~/Dropbox/ansible-openmpi/playbooks/.ssh/tmp/ dest=~/.ssh/tmp recursive=yes
  - name: Adding to the list of authorized_keys  
    shell: cat ~/.ssh/tmp/166.78.164.*/root/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
